import irc

config = {
    # Server to connect too
    'server': 'irc.chat.twitch.tv',

    # Port of server to connect too
    'port': 6667,
	
    # Username to use in client
    'username': 'twitchfightsbots',

    # This is an oauth string generated by twitch
    'password': 'oauth:hb9xv391gwcftx7h6c3bvtabwimhjz',

    'channel': '#twitchfightsbots'
}

class ApplicationServer(object):
    def __init__(self, config):
        self.irc = irc.irc(config)

    def run(self):
        while True:
            print(self.irc.recieve_message())

if __name__ == '__main__':
    app = ApplicationServer(config)
    app.run()
